substitutions:
  device_name: magiqtouch-hvac
  friendly_name: MagIQTouch HVAC Control
  # Pin definitions for WiFi boards (default)
  uart_rx_pin: "26"
  uart_tx_pin: "27"
  rs485_en_pin: "18"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "MagIQTouch Modbus HVAC Controller - ESPHome Edition"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 0  # Disable logging over UART to avoid conflicts

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Power settings for better reliability
  power_save_mode: none
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Web server for monitoring
web_server:
  port: 80
  version: 2

# External components - load magiqtouch from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/splitice/magiqtouch-modbus-esp32
      ref: main
    components: [magiqtouch]
    refresh: 0s

# Single UART Configuration for RS485 Modbus network
uart:
  - id: uart_modbus
    tx_pin: GPIO${uart_tx_pin}
    rx_pin: GPIO${uart_rx_pin}
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

# MagiqTouch Component (simplified - no climate)
magiqtouch:
  id: magiqtouch_controller
  uart_id: uart_modbus
  rs485_enable_pin: GPIO${rs485_en_pin}
  thermistor_temp_sensor: thermistor_temp_sensor
  drain_mode_active_sensor: drain_mode_active_sensor
  system_mode_sensor: system_mode_sensor

# Sensors from the MagiqTouch system
sensor:
  - platform: template
    name: "${friendly_name} Thermistor Temperature"
    id: thermistor_temp_sensor
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 0

# Binary sensors
binary_sensor:
  - platform: template
    name: "${friendly_name} Drain Mode Active"
    id: drain_mode_active_sensor

# Text sensors
text_sensor:
  - platform: template
    name: "${friendly_name} System Mode"
    id: system_mode_sensor

# Control Buttons
button:
  - platform: template
    name: "${friendly_name} Power ON"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_power(true);
  
  - platform: template
    name: "${friendly_name} Power OFF"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_power(false);
  
  - platform: template
    name: "${friendly_name} Mode: Fan External"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(0);
  
  - platform: template
    name: "${friendly_name} Mode: Fan Recycle"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(1);
  
  - platform: template
    name: "${friendly_name} Mode: Cooler Manual"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(2);
  
  - platform: template
    name: "${friendly_name} Mode: Cooler Auto"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(3);
  
  - platform: template
    name: "${friendly_name} Mode: Heater"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(4);
  
  - platform: template
    name: "${friendly_name} Trigger Drain Mode"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->trigger_drain_mode();
  
  - platform: template
    name: "${friendly_name} Cancel Drain Mode"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->cancel_drain_mode();

# Number controls
number:
  - platform: template
    name: "${friendly_name} Fan Speed"
    id: fan_speed_control
    min_value: 0
    max_value: 10
    step: 1
    initial_value: 5
    optimistic: true
    set_action:
      - lambda: |-
          id(magiqtouch_controller)->set_fan_speed((uint8_t)x);
