substitutions:
  device_name: magiqtouch-hvac
  friendly_name: MagIQTouch HVAC Control
  # Pin definitions for WiFi boards (default)
  serial1_rx_pin: "26"
  serial1_tx_pin: "27"
  serial2_rx_pin: "16"
  serial2_tx_pin: "17"
  rs485_en_pin: "18"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "MagIQTouch Modbus HVAC Controller - ESPHome Edition"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 0  # Disable logging over UART to avoid conflicts

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Power settings for better reliability
  power_save_mode: none
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Web server for REST API compatibility
web_server:
  port: 80
  version: 2
  include_internal: true
  ota: false

# UART Configuration for RS485 communication
# UART 1 - Control Panel connection
uart:
  - id: uart_panel
    tx_pin: GPIO${serial1_tx_pin}
    rx_pin: GPIO${serial1_rx_pin}
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    # debug:
    #   direction: BOTH
  
  # UART 2 - Unit connection
  - id: uart_unit
    tx_pin: GPIO${serial2_tx_pin}
    rx_pin: GPIO${serial2_rx_pin}
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    # debug:
    #   direction: BOTH

# Interval-based components
interval:
  - interval: 5s
    then:
      - lambda: |-
          // Placeholder for periodic tasks
          // In full implementation, this would handle drain mode timing
          // and periodic status updates

# Status LED (optional - adjust pin as needed)
# status_led:
#   pin:
#     number: GPIO2
#     inverted: false
