esphome:
  name: roofevap1
  friendly_name: RoofEvap1
  min_version: 2025.11.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32c3
  framework:
    type: esp-idf
    sdkconfig_options: 
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y 
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10" 
      variant: ESP32C3

ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 8MHz
  manual_ip:
    static_ip: 192.168.1.118
    gateway: 192.168.1.1
    dns1: 192.168.1.1
    subnet: 255.255.255.0

api:
  encryption:
    key: "MrZOsHwOPNQfpVX+U1hrkmQozSUAVqicVffuEJXlawY="
logger:
ota:
  - platform: esphome
    id: ota_esphome
    password: "c3f575209e398c4c22b1ddd8b468f86e"

esp32_ble:
  max_connections: 2

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 100ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 2

external_components:
- source:
    type: git
    url: https://github.com/splitice/magiqtouch-modbus-esp32.git
    ref: copilot/rework-aircon-control-to-esphome
  components: [ magiqtouch ]
  refresh: 1s

substitutions:
  device_name: magiqtouch-hvac
  friendly_name: Evap
  # Pin definitions for WiFi boards (default)
  uart_rx_pin: "7"
  uart_tx_pin: "8"
  rs485_en_pin: "6"


# Single UART Configuration for RS485 Modbus network
uart:
  - id: uart_modbus
    tx_pin: GPIO${uart_tx_pin}
    rx_pin: GPIO${uart_rx_pin}
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

# MagiqTouch Component (simplified - no climate, no IoT temp sensors)
magiqtouch:
  id: magiqtouch_controller
  uart_id: uart_modbus
  rs485_enable_pin: GPIO${rs485_en_pin}
  drain_mode_active_sensor: drain_mode_active_sensor
  system_mode_sensor: system_mode_sensor

# Sensors from the MagiqTouch system
sensor:
  - platform: uptime
    name: "RoofEvap Uptime"

# Binary sensors
binary_sensor:
  - platform: template
    name: "${friendly_name} Drain Mode Active"
    id: drain_mode_active_sensor

# Text sensors
text_sensor:
  - platform: template
    name: "${friendly_name} System Mode"
    id: system_mode_sensor

# Control Buttons
button:
  - platform: template
    name: "${friendly_name} Power ON"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_power(true);
  
  - platform: template
    name: "${friendly_name} Power OFF"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_power(false);
  
  - platform: template
    name: "${friendly_name} Mode: Fan External"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(0);
  
  - platform: template
    name: "${friendly_name} Mode: Fan Recycle"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(1);
  
  - platform: template
    name: "${friendly_name} Mode: Cooler Manual"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(2);
  
  - platform: template
    name: "${friendly_name} Mode: Cooler Auto"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(3);
  
  - platform: template
    name: "${friendly_name} Mode: Heater"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->set_mode(4);
  
  - platform: template
    name: "${friendly_name} Trigger Drain Mode"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->trigger_drain_mode();
  
  - platform: template
    name: "${friendly_name} Cancel Drain Mode"
    on_press:
      - lambda: |-
          id(magiqtouch_controller)->cancel_drain_mode();

# Number controls
number:
  - platform: template
    name: "${friendly_name} Fan Speed"
    id: fan_speed_control
    min_value: 0
    max_value: 10
    step: 1
    initial_value: 5
    optimistic: true
    set_action:
      - lambda: |-
          id(magiqtouch_controller)->set_fan_speed((uint8_t)x);
